// Unified leaderboard configuration for all themes

export interface LeaderboardPlayer {
  rank: number;
  name: string;
  level: number;
  currency: number; // Main theme currency (Championships, V-Bucks, Diamonds, etc.)
  powerLevel: number; // Universal power metric
  achievements: number; // Theme-specific achievement count
  change: number;
  avatar: string;
}

export interface LeaderboardLabels {
  title: string;
  subtitle: string;
  topLabel: string;
  playerLabel: string;
  currencyLabel: string;
  powerLevelLabel: string;
  achievementsLabel: string;
  statCard1Label: string;
  statCard2Label: string;
  statCard3Label: string;
  liveCounterText: string; // e.g., "students learning RIGHT NOW"
  topPercentText: string; // e.g., "You're in the TOP {percent}% worldwide!"
  rankContextText: string; // e.g., "Compete with students worldwide!"
}

export const themeLeaderboardConfig: Record<string, LeaderboardLabels> = {
  default: {
    title: 'GLOBAL RANKINGS',
    subtitle: 'Compete with learners worldwide!',
    topLabel: 'TOP STUDENTS',
    playerLabel: 'Student',
    currencyLabel: 'Coins',
    powerLevelLabel: 'Power Level',
    achievementsLabel: 'Achievements',
    statCard1Label: 'Total Coins',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'students learning RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% worldwide!",
    rankContextText: 'Compete with students worldwide!',
  },
  dinosaur: {
    title: 'PREHISTORIC RANKINGS',
    subtitle: 'Stomp your way to the top of the dino world!',
    topLabel: 'TOP PALEONTOLOGISTS',
    playerLabel: 'Explorer',
    currencyLabel: 'Dino Bones',
    powerLevelLabel: 'Fossils Found',
    achievementsLabel: 'Discoveries',
    statCard1Label: 'Dino Bones',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'explorers digging RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of paleontologists!",
    rankContextText: 'Dig deeper than the competition!',
  },
  battle: {
    title: 'BATTLE RANKINGS',
    subtitle: 'Fight your way to victory!',
    topLabel: 'TOP WARRIORS',
    playerLabel: 'Fighter',
    currencyLabel: 'Battle Points',
    powerLevelLabel: 'Battles Won',
    achievementsLabel: 'Victory Streak',
    statCard1Label: 'Battle Points',
    statCard2Label: 'Win Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'warriors fighting RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of fighters!",
    rankContextText: 'Defeat them all!',
  },
  builder: {
    title: 'MASTER BUILDER RANKINGS',
    subtitle: 'Craft your way to legendary status!',
    topLabel: 'TOP BUILDERS',
    playerLabel: 'Builder',
    currencyLabel: 'Emeralds',
    powerLevelLabel: 'Blocks Placed',
    achievementsLabel: 'Builds',
    statCard1Label: 'Emeralds',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'builders crafting RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of builders!",
    rankContextText: 'Build your legacy!',
  },
  unicorn: {
    title: 'MAGICAL RANKINGS',
    subtitle: 'Spread magic across the kingdom!',
    topLabel: 'TOP UNICORNS',
    playerLabel: 'Unicorn',
    currencyLabel: 'Magic Gems',
    powerLevelLabel: 'Magic Power',
    achievementsLabel: 'Spells Cast',
    statCard1Label: 'Magic Gems',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'unicorns spreading magic RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of magical beings!",
    rankContextText: 'Spread the magic!',
  },
  space: {
    title: 'GALACTIC RANKINGS',
    subtitle: 'Explore the final frontier!',
    topLabel: 'TOP ASTRONAUTS',
    playerLabel: 'Explorer',
    currencyLabel: 'Star Dust',
    powerLevelLabel: 'Planets Visited',
    achievementsLabel: 'Discoveries',
    statCard1Label: 'Star Dust',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'astronauts exploring RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of space explorers!",
    rankContextText: 'Reach for the stars!',
  },
  robot: {
    title: 'ROBOT RANKINGS',
    subtitle: 'Compute your way to the top!',
    topLabel: 'TOP ROBOTS',
    playerLabel: 'Bot',
    currencyLabel: 'Bot Bolts',
    powerLevelLabel: 'Circuits Built',
    achievementsLabel: 'Upgrades',
    statCard1Label: 'Bot Bolts',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'robots computing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of bots!",
    rankContextText: 'Upgrade your circuits!',
  },
  pirate: {
    title: 'PIRATE RANKINGS',
    subtitle: 'Who will rule the seven seas?',
    topLabel: 'TOP PIRATES',
    playerLabel: 'Pirate',
    currencyLabel: 'Gold Doubloons',
    powerLevelLabel: 'Treasures Found',
    achievementsLabel: 'Islands Conquered',
    statCard1Label: 'Doubloons',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'pirates sailing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of pirates!",
    rankContextText: 'Rule the seven seas!',
  },
  monster: {
    title: 'MONSTER TRUCK RANKINGS',
    subtitle: 'Crush the competition!',
    topLabel: 'TOP DRIVERS',
    playerLabel: 'Driver',
    currencyLabel: 'Turbo Points',
    powerLevelLabel: 'Jumps Completed',
    achievementsLabel: 'Races Won',
    statCard1Label: 'Turbo Points',
    statCard2Label: 'Win Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'drivers racing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of drivers!",
    rankContextText: 'Crush the competition!',
  },
  hero: {
    title: 'HERO RANKINGS',
    subtitle: 'Save the day and rise to the top!',
    topLabel: 'TOP HEROES',
    playerLabel: 'Hero',
    currencyLabel: 'Hero Points',
    powerLevelLabel: 'Villains Defeated',
    achievementsLabel: 'Rescues',
    statCard1Label: 'Hero Points',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'heroes saving the day RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of heroes!",
    rankContextText: 'Save the world!',
  },
  dreams: {
    title: 'UNICORN DREAM RANKINGS',
    subtitle: 'Follow your dreams to the top!',
    topLabel: 'TOP DREAMERS',
    playerLabel: 'Dreamer',
    currencyLabel: 'Rainbow Gems',
    powerLevelLabel: 'Dreams Achieved',
    achievementsLabel: 'Magic Moments',
    statCard1Label: 'Rainbow Gems',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'dreamers dreaming RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of dreamers!",
    rankContextText: 'Follow your dreams!',
  },
  mermaid: {
    title: 'OCEAN RANKINGS',
    subtitle: 'Dive deep and rule the seas!',
    topLabel: 'TOP MERMAIDS',
    playerLabel: 'Mermaid',
    currencyLabel: 'Sea Pearls',
    powerLevelLabel: 'Depths Explored',
    achievementsLabel: 'Treasures Found',
    statCard1Label: 'Sea Pearls',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'mermaids swimming RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of ocean dwellers!",
    rankContextText: 'Dive deeper!',
  },
  princess: {
    title: 'ROYAL RANKINGS',
    subtitle: 'Rule your kingdom with grace!',
    topLabel: 'TOP ROYALTY',
    playerLabel: 'Princess',
    currencyLabel: 'Royal Jewels',
    powerLevelLabel: 'Royal Decrees',
    achievementsLabel: 'Balls Hosted',
    statCard1Label: 'Royal Jewels',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'princesses ruling RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of royalty!",
    rankContextText: 'Rule with grace!',
  },
  rainbow: {
    title: 'RAINBOW RANKINGS',
    subtitle: 'Paint the world with color!',
    topLabel: 'TOP ARTISTS',
    playerLabel: 'Artist',
    currencyLabel: 'Color Stars',
    powerLevelLabel: 'Rainbows Created',
    achievementsLabel: 'Masterpieces',
    statCard1Label: 'Color Stars',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'artists creating RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of artists!",
    rankContextText: 'Paint the world!',
  },
  victory: {
    title: 'VICTORY RANKINGS',
    subtitle: 'Claim your Victory Royale!',
    topLabel: 'TOP VICTORS',
    playerLabel: 'Champion',
    currencyLabel: 'V-Points',
    powerLevelLabel: 'Eliminations',
    achievementsLabel: 'Wins',
    statCard1Label: 'V-Points',
    statCard2Label: 'Win Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'players dropping RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of warriors!",
    rankContextText: 'Claim your victory!',
  },
  cube: {
    title: 'CUBE CRAFT RANKINGS',
    subtitle: 'Build and mine your way up!',
    topLabel: 'TOP CRAFTERS',
    playerLabel: 'Crafter',
    currencyLabel: 'Emeralds',
    powerLevelLabel: 'Blocks Mined',
    achievementsLabel: 'Builds',
    statCard1Label: 'Emeralds',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'crafters mining RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of miners!",
    rankContextText: 'Mine and craft!',
  },
  web: {
    title: 'WEB WARRIOR RANKINGS',
    subtitle: 'Swing to the top!',
    topLabel: 'TOP HEROES',
    playerLabel: 'Hero',
    currencyLabel: 'Web Points',
    powerLevelLabel: 'Villains Caught',
    achievementsLabel: 'Rescues',
    statCard1Label: 'Web Points',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'heroes swinging RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of web warriors!",
    rankContextText: 'Swing to the top!',
  },
  creatures: {
    title: 'CREATURE RANKINGS',
    subtitle: 'Catch them all!',
    topLabel: 'TOP TRAINERS',
    playerLabel: 'Trainer',
    currencyLabel: 'Poké Coins',
    powerLevelLabel: 'Creatures Caught',
    achievementsLabel: 'Badges Earned',
    statCard1Label: 'Poké Coins',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'trainers catching RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of trainers!",
    rankContextText: 'Catch them all!',
  },
  glam: {
    title: 'GLAM RANKINGS',
    subtitle: 'Shine bright like a diamond!',
    topLabel: 'TOP DOLLS',
    playerLabel: 'Doll',
    currencyLabel: 'Glam Bucks',
    powerLevelLabel: 'Style Points',
    achievementsLabel: 'Outfits Created',
    statCard1Label: 'Glam Bucks',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'dolls shining RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of fashionistas!",
    rankContextText: 'Shine bright!',
  },
  fashion: {
    title: 'FASHION RANKINGS',
    subtitle: 'Walk the runway to success!',
    topLabel: 'TOP FASHIONISTAS',
    playerLabel: 'Designer',
    currencyLabel: 'Style Points',
    powerLevelLabel: 'Fashion Shows',
    achievementsLabel: 'Collections',
    statCard1Label: 'Style Points',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'designers creating RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of fashion icons!",
    rankContextText: 'Walk the runway!',
  },
  ice: {
    title: 'FROZEN RANKINGS',
    subtitle: 'Let it go and rise to power!',
    topLabel: 'TOP ROYALTY',
    playerLabel: 'Ice Queen',
    currencyLabel: 'Ice Crystals',
    powerLevelLabel: 'Frost Power',
    achievementsLabel: 'Castles Built',
    statCard1Label: 'Ice Crystals',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'ice queens reigning RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of frost royalty!",
    rankContextText: 'Let it go!',
  },
  pony: {
    title: 'PONY RANKINGS',
    subtitle: 'Gallop to greatness!',
    topLabel: 'TOP RANCHERS',
    playerLabel: 'Rider',
    currencyLabel: 'Friendship Hearts',
    powerLevelLabel: 'Ponies Trained',
    achievementsLabel: 'Friendships',
    statCard1Label: 'Friendship Hearts',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'riders galloping RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of ranchers!",
    rankContextText: 'Ride to victory!',
  },
  neon: {
    title: 'GAMER RANKINGS',
    subtitle: 'Level up your game!',
    topLabel: 'TOP GAMERS',
    playerLabel: 'Gamer',
    currencyLabel: 'XP Points',
    powerLevelLabel: 'High Scores',
    achievementsLabel: 'Games Mastered',
    statCard1Label: 'XP Points',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'gamers playing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of gamers!",
    rankContextText: 'Level up!',
  },
  anime: {
    title: 'ANIME HERO RANKINGS',
    subtitle: 'Train to become the strongest!',
    topLabel: 'TOP HEROES',
    playerLabel: 'Hero',
    currencyLabel: 'Power Orbs',
    powerLevelLabel: 'Power Level',
    achievementsLabel: 'Battles Won',
    statCard1Label: 'Power Orbs',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'heroes training RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of warriors!",
    rankContextText: 'Become the strongest!',
  },
  sneaker: {
    title: 'SNEAKER RANKINGS',
    subtitle: 'Step up your game!',
    topLabel: 'TOP SNEAKERHEADS',
    playerLabel: 'Collector',
    currencyLabel: 'Hype Points',
    powerLevelLabel: 'Sneakers Owned',
    achievementsLabel: 'Rare Finds',
    statCard1Label: 'Hype Points',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'collectors flexing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of sneakerheads!",
    rankContextText: 'Cop the heat!',
  },
  esports: {
    title: 'ESPORTS RANKINGS',
    subtitle: 'Compete at the highest level!',
    topLabel: 'TOP PROS',
    playerLabel: 'Pro',
    currencyLabel: 'Pro Credits',
    powerLevelLabel: 'Tournaments Won',
    achievementsLabel: 'MVP Awards',
    statCard1Label: 'Pro Credits',
    statCard2Label: 'Win Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'pros competing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of pros!",
    rankContextText: 'Go pro!',
  },
  aesthetic: {
    title: 'AESTHETIC RANKINGS',
    subtitle: 'Vibe your way to the top!',
    topLabel: 'TOP INFLUENCERS',
    playerLabel: 'Influencer',
    currencyLabel: 'Aesthetic Points',
    powerLevelLabel: 'Posts Created',
    achievementsLabel: 'Followers',
    statCard1Label: 'Aesthetic Points',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'influencers vibing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of creators!",
    rankContextText: 'Keep the aesthetic!',
  },
  kpop: {
    title: 'K-POP RANKINGS',
    subtitle: 'Dance to the top of the charts!',
    topLabel: 'TOP IDOLS',
    playerLabel: 'Idol',
    currencyLabel: 'Fan Hearts',
    powerLevelLabel: 'Songs Released',
    achievementsLabel: 'Awards Won',
    statCard1Label: 'Fan Hearts',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'idols performing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of idols!",
    rankContextText: 'Top the charts!',
  },
  softgirl: {
    title: 'SOFT GIRL RANKINGS',
    subtitle: 'Stay soft and reach the clouds!',
    topLabel: 'TOP SOFT GIRLS',
    playerLabel: 'Soft Girl',
    currencyLabel: 'Cloud Puffs',
    powerLevelLabel: 'Aesthetic Vibes',
    achievementsLabel: 'Outfits',
    statCard1Label: 'Cloud Puffs',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'soft girls vibing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of soft souls!",
    rankContextText: 'Stay soft!',
  },
  cottagecore: {
    title: 'COTTAGECORE RANKINGS',
    subtitle: 'Garden your way to peace!',
    topLabel: 'TOP GARDENERS',
    playerLabel: 'Gardener',
    currencyLabel: 'Acorns',
    powerLevelLabel: 'Plants Grown',
    achievementsLabel: 'Harvests',
    statCard1Label: 'Acorns',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'gardeners growing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of gardeners!",
    rankContextText: 'Grow your garden!',
  },
  minimal: {
    title: 'MINIMAL RANKINGS',
    subtitle: 'Less is more, rise with simplicity!',
    topLabel: 'TOP MINIMALISTS',
    playerLabel: 'Minimalist',
    currencyLabel: 'Credits',
    powerLevelLabel: 'Tasks Completed',
    achievementsLabel: 'Goals Achieved',
    statCard1Label: 'Credits',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'minimalists simplifying RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of minimalists!",
    rankContextText: 'Less is more!',
  },
  cyberpunk: {
    title: 'CYBERPUNK RANKINGS',
    subtitle: 'Jack into the grid and dominate!',
    topLabel: 'TOP RUNNERS',
    playerLabel: 'Runner',
    currencyLabel: 'Data Bits',
    powerLevelLabel: 'Systems Hacked',
    achievementsLabel: 'Missions',
    statCard1Label: 'Data Bits',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'runners jacking in RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of netrunners!",
    rankContextText: 'Jack into greatness!',
  },
  coder: {
    title: 'CODER RANKINGS',
    subtitle: 'Code your way to the top!',
    topLabel: 'TOP DEVELOPERS',
    playerLabel: 'Developer',
    currencyLabel: 'Tokens',
    powerLevelLabel: 'Lines Coded',
    achievementsLabel: 'Projects',
    statCard1Label: 'Tokens',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'developers coding RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of developers!",
    rankContextText: 'Code your future!',
  },
  streetwear: {
    title: 'STREETWEAR RANKINGS',
    subtitle: 'Drop fire fits and collect clout!',
    topLabel: 'TOP HYPEBEASTS',
    playerLabel: 'Hypebeast',
    currencyLabel: 'Clout Points',
    powerLevelLabel: 'Fits Posted',
    achievementsLabel: 'Drops Copped',
    statCard1Label: 'Clout Points',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'hypebeasts flexing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of hypebeasts!",
    rankContextText: 'Drip or drown!',
  },
  shark: {
    title: 'SHARK RANKINGS',
    subtitle: 'Swim with the sharks!',
    topLabel: 'TOP PREDATORS',
    playerLabel: 'Shark',
    currencyLabel: 'Shark Teeth',
    powerLevelLabel: 'Prey Caught',
    achievementsLabel: 'Territory',
    statCard1Label: 'Shark Teeth',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'sharks hunting RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of predators!",
    rankContextText: 'Rule the ocean!',
  },
  butterfly: {
    title: 'BUTTERFLY RANKINGS',
    subtitle: 'Flutter your way to beauty!',
    topLabel: 'TOP BUTTERFLIES',
    playerLabel: 'Butterfly',
    currencyLabel: 'Flutter Gems',
    powerLevelLabel: 'Flowers Visited',
    achievementsLabel: 'Gardens',
    statCard1Label: 'Flutter Gems',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'butterflies fluttering RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of butterflies!",
    rankContextText: 'Flutter higher!',
  },
  kitten: {
    title: 'KITTEN RANKINGS',
    subtitle: 'Purr your way to the top!',
    topLabel: 'TOP KITTENS',
    playerLabel: 'Kitten',
    currencyLabel: 'Kitty Treats',
    powerLevelLabel: 'Cuddles Given',
    achievementsLabel: 'Toys Played',
    statCard1Label: 'Kitty Treats',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'kittens playing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of kittens!",
    rankContextText: 'Purr your way up!',
  },
  fairy: {
    title: 'FAIRY RANKINGS',
    subtitle: 'Sprinkle magic everywhere!',
    topLabel: 'TOP FAIRIES',
    playerLabel: 'Fairy',
    currencyLabel: 'Fairy Dust',
    powerLevelLabel: 'Spells Cast',
    achievementsLabel: 'Wishes Granted',
    statCard1Label: 'Fairy Dust',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'fairies flying RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of fairies!",
    rankContextText: 'Spread your magic!',
  },
  ballerina: {
    title: 'BALLERINA RANKINGS',
    subtitle: 'Dance with grace and elegance!',
    topLabel: 'TOP DANCERS',
    playerLabel: 'Ballerina',
    currencyLabel: 'Ballet Stars',
    powerLevelLabel: 'Performances',
    achievementsLabel: 'Recitals',
    statCard1Label: 'Ballet Stars',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'dancers performing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of dancers!",
    rankContextText: 'Dance to perfection!',
  },
  ninja: {
    title: 'NINJA RANKINGS',
    subtitle: 'Master the shadow arts!',
    topLabel: 'TOP NINJAS',
    playerLabel: 'Ninja',
    currencyLabel: 'Shuriken',
    powerLevelLabel: 'Missions Complete',
    achievementsLabel: 'Belts Earned',
    statCard1Label: 'Shuriken',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'ninjas training RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of ninjas!",
    rankContextText: 'Master the shadows!',
  },
  zombie: {
    title: 'ZOMBIE SURVIVAL RANKINGS',
    subtitle: 'Survive the apocalypse!',
    topLabel: 'TOP SURVIVORS',
    playerLabel: 'Survivor',
    currencyLabel: 'Survival Kits',
    powerLevelLabel: 'Zombies Killed',
    achievementsLabel: 'Days Survived',
    statCard1Label: 'Survival Kits',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'survivors fighting RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of survivors!",
    rankContextText: 'Survive the apocalypse!',
  },
  racecar: {
    title: 'RACING RANKINGS',
    subtitle: 'Speed to victory!',
    topLabel: 'TOP RACERS',
    playerLabel: 'Racer',
    currencyLabel: 'Speed Tokens',
    powerLevelLabel: 'Races Won',
    achievementsLabel: 'Championships',
    statCard1Label: 'Speed Tokens',
    statCard2Label: 'Win Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'racers speeding RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of racers!",
    rankContextText: 'Speed to victory!',
  },
  mech: {
    title: 'MECH PILOT RANKINGS',
    subtitle: 'Command your mech to victory!',
    topLabel: 'TOP PILOTS',
    playerLabel: 'Pilot',
    currencyLabel: 'Mech Parts',
    powerLevelLabel: 'Battles Won',
    achievementsLabel: 'Mechs Built',
    statCard1Label: 'Mech Parts',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'pilots battling RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of pilots!",
    rankContextText: 'Command your mech!',
  },
  popstar: {
    title: 'POP STAR RANKINGS',
    subtitle: 'Sing your way to stardom!',
    topLabel: 'TOP STARS',
    playerLabel: 'Star',
    currencyLabel: 'Star Points',
    powerLevelLabel: 'Concerts Held',
    achievementsLabel: 'Hit Songs',
    statCard1Label: 'Star Points',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'stars performing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of stars!",
    rankContextText: 'Shine on stage!',
  },
  cupcake: {
    title: 'BAKER RANKINGS',
    subtitle: 'Bake your way to sweetness!',
    topLabel: 'TOP BAKERS',
    playerLabel: 'Baker',
    currencyLabel: 'Sprinkles',
    powerLevelLabel: 'Cupcakes Baked',
    achievementsLabel: 'Recipes',
    statCard1Label: 'Sprinkles',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'bakers baking RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of bakers!",
    rankContextText: 'Sweeten the world!',
  },
  friendship: {
    title: 'FRIENDSHIP RANKINGS',
    subtitle: 'Share the love!',
    topLabel: 'TOP FRIENDS',
    playerLabel: 'Friend',
    currencyLabel: 'Friend Hearts',
    powerLevelLabel: 'Friendships Made',
    achievementsLabel: 'Hangouts',
    statCard1Label: 'Friend Hearts',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'friends connecting RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of friends!",
    rankContextText: 'Share the love!',
  },
  kawaii: {
    title: 'KAWAII RANKINGS',
    subtitle: 'Spread cuteness everywhere!',
    topLabel: 'TOP CUTIES',
    playerLabel: 'Cutie',
    currencyLabel: 'Kawaii Stars',
    powerLevelLabel: 'Cuteness Level',
    achievementsLabel: 'Friends Made',
    statCard1Label: 'Kawaii Stars',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'cuties spreading joy RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of kawaii!",
    rankContextText: 'Stay cute!',
  },
  graffiti: {
    title: 'STREET ART RANKINGS',
    subtitle: 'Tag your way to the top!',
    topLabel: 'TOP ARTISTS',
    playerLabel: 'Artist',
    currencyLabel: 'Spray Cans',
    powerLevelLabel: 'Murals Created',
    achievementsLabel: 'Walls Tagged',
    statCard1Label: 'Spray Cans',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'artists tagging RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of street artists!",
    rankContextText: 'Tag your mark!',
  },
  hiphop: {
    title: 'HIP HOP RANKINGS',
    subtitle: 'Drop beats and rise up!',
    topLabel: 'TOP MCS',
    playerLabel: 'MC',
    currencyLabel: 'Beats',
    powerLevelLabel: 'Tracks Dropped',
    achievementsLabel: 'Cyphers Won',
    statCard1Label: 'Beats',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'MCs dropping bars RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of MCs!",
    rankContextText: 'Drop the beat!',
  },
  scifi: {
    title: 'SCI-FI RANKINGS',
    subtitle: 'Explore the future!',
    topLabel: 'TOP EXPLORERS',
    playerLabel: 'Explorer',
    currencyLabel: 'Quantum Cells',
    powerLevelLabel: 'Tech Discovered',
    achievementsLabel: 'Worlds Visited',
    statCard1Label: 'Quantum Cells',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'explorers discovering RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of explorers!",
    rankContextText: 'Explore the future!',
  },
  darkninja: {
    title: 'SHADOW RANKINGS',
    subtitle: 'Strike from the darkness!',
    topLabel: 'TOP ASSASSINS',
    playerLabel: 'Assassin',
    currencyLabel: 'Shadow Coins',
    powerLevelLabel: 'Missions Complete',
    achievementsLabel: 'Targets Hit',
    statCard1Label: 'Shadow Coins',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'assassins striking RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of shadows!",
    rankContextText: 'Strike from darkness!',
  },
  y2k: {
    title: 'Y2K RANKINGS',
    subtitle: 'Take it back to the 2000s!',
    topLabel: 'TOP TRENDSETTERS',
    playerLabel: 'Trendsetter',
    currencyLabel: 'Glitter Bits',
    powerLevelLabel: 'Trends Set',
    achievementsLabel: 'Throwbacks',
    statCard1Label: 'Glitter Bits',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'trendsetters vibing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of trendsetters!",
    rankContextText: 'Bring back Y2K!',
  },
  zodiac: {
    title: 'ZODIAC RANKINGS',
    subtitle: 'Let the stars guide you!',
    topLabel: 'TOP ASTROLOGERS',
    playerLabel: 'Astrologer',
    currencyLabel: 'Star Signs',
    powerLevelLabel: 'Readings Done',
    achievementsLabel: 'Horoscopes',
    statCard1Label: 'Star Signs',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'astrologers reading RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of mystics!",
    rankContextText: 'Read the stars!',
  },
  bookworm: {
    title: 'BOOKWORM RANKINGS',
    subtitle: 'Read your way to wisdom!',
    topLabel: 'TOP READERS',
    playerLabel: 'Reader',
    currencyLabel: 'Book Pages',
    powerLevelLabel: 'Books Read',
    achievementsLabel: 'Libraries Visited',
    statCard1Label: 'Book Pages',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'readers reading RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of bookworms!",
    rankContextText: 'Read your way up!',
  },
  dance: {
    title: 'DANCE RANKINGS',
    subtitle: 'Move to the rhythm!',
    topLabel: 'TOP DANCERS',
    playerLabel: 'Dancer',
    currencyLabel: 'Dance Moves',
    powerLevelLabel: 'Routines Learned',
    achievementsLabel: 'Competitions Won',
    statCard1Label: 'Dance Moves',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'dancers moving RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of dancers!",
    rankContextText: 'Move to the rhythm!',
  },
  lofi: {
    title: 'LO-FI RANKINGS',
    subtitle: 'Chill and vibe to the top!',
    topLabel: 'TOP CHILLSTERS',
    playerLabel: 'Viber',
    currencyLabel: 'Chill Points',
    powerLevelLabel: 'Playlists Created',
    achievementsLabel: 'Study Sessions',
    statCard1Label: 'Chill Points',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'chillsters vibing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of chill souls!",
    rankContextText: 'Keep it chill!',
  },
  finance: {
    title: 'FINANCE RANKINGS',
    subtitle: 'Stack that money!',
    topLabel: 'TOP TRADERS',
    playerLabel: 'Trader',
    currencyLabel: 'Crypto',
    powerLevelLabel: 'Trades Made',
    achievementsLabel: 'Portfolio Value',
    statCard1Label: 'Crypto',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'traders trading RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of traders!",
    rankContextText: 'Stack that money!',
  },
  gym: {
    title: 'GYM RANKINGS',
    subtitle: 'Lift your way to gains!',
    topLabel: 'TOP ATHLETES',
    playerLabel: 'Athlete',
    currencyLabel: 'Gains',
    powerLevelLabel: 'Weight Lifted',
    achievementsLabel: 'PRs Hit',
    statCard1Label: 'Gains',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'athletes lifting RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of athletes!",
    rankContextText: 'Get those gains!',
  },
  nightowl: {
    title: 'NIGHT OWL RANKINGS',
    subtitle: 'Own the night!',
    topLabel: 'TOP NIGHT OWLS',
    playerLabel: 'Night Owl',
    currencyLabel: 'Moon Phases',
    powerLevelLabel: 'Late Nights',
    achievementsLabel: 'Tasks Completed',
    statCard1Label: 'Moon Phases',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'night owls working RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of night owls!",
    rankContextText: 'Own the night!',
  },
  cleangirl: {
    title: 'CLEAN GIRL RANKINGS',
    subtitle: 'Glow naturally!',
    topLabel: 'TOP CLEAN GIRLS',
    playerLabel: 'Clean Girl',
    currencyLabel: 'Glow Points',
    powerLevelLabel: 'Routines Done',
    achievementsLabel: 'Self Care Days',
    statCard1Label: 'Glow Points',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'clean girls glowing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of clean girls!",
    rankContextText: 'Glow naturally!',
  },
  sage: {
    title: 'SAGE RANKINGS',
    subtitle: 'Find your inner peace!',
    topLabel: 'TOP SAGES',
    playerLabel: 'Sage',
    currencyLabel: 'Sage Leaves',
    powerLevelLabel: 'Meditations',
    achievementsLabel: 'Wisdom Gained',
    statCard1Label: 'Sage Leaves',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'sages meditating RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of wise souls!",
    rankContextText: 'Find your peace!',
  },
  coffee: {
    title: 'COFFEE RANKINGS',
    subtitle: 'Brew your way up!',
    topLabel: 'TOP BARISTAS',
    playerLabel: 'Barista',
    currencyLabel: 'Coffee Beans',
    powerLevelLabel: 'Cups Brewed',
    achievementsLabel: 'Recipes Mastered',
    statCard1Label: 'Coffee Beans',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'baristas brewing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of baristas!",
    rankContextText: 'Brew greatness!',
  },
  study: {
    title: 'STUDY RANKINGS',
    subtitle: 'Study smart, succeed!',
    topLabel: 'TOP SCHOLARS',
    playerLabel: 'Scholar',
    currencyLabel: 'Study Hours',
    powerLevelLabel: 'Tests Aced',
    achievementsLabel: 'Subjects Mastered',
    statCard1Label: 'Study Hours',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'scholars studying RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of scholars!",
    rankContextText: 'Study smart!',
  },
  parisian: {
    title: 'PARISIAN RANKINGS',
    subtitle: 'Embrace French elegance!',
    topLabel: 'TOP PARISIANS',
    playerLabel: 'Parisian',
    currencyLabel: 'Étoiles',
    powerLevelLabel: 'Style Level',
    achievementsLabel: 'Outfits Created',
    statCard1Label: 'Étoiles',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'Parisians styling RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of Parisians!",
    rankContextText: 'Embrace elegance!',
  },
  wellness: {
    title: 'WELLNESS RANKINGS',
    subtitle: 'Balance mind, body, and soul!',
    topLabel: 'TOP WELLNESS GURUS',
    playerLabel: 'Guru',
    currencyLabel: 'Zen Points',
    powerLevelLabel: 'Sessions Done',
    achievementsLabel: 'Practices Mastered',
    statCard1Label: 'Zen Points',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'gurus practicing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of wellness warriors!",
    rankContextText: 'Balance your life!',
  },
  vintage: {
    title: 'VINTAGE RANKINGS',
    subtitle: 'Timeless style never fades!',
    topLabel: 'TOP COLLECTORS',
    playerLabel: 'Collector',
    currencyLabel: 'Antique Coins',
    powerLevelLabel: 'Items Collected',
    achievementsLabel: 'Rare Finds',
    statCard1Label: 'Antique Coins',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'collectors collecting RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of collectors!",
    rankContextText: 'Collect the classics!',
  },
  moonlight: {
    title: 'MOONLIGHT RANKINGS',
    subtitle: 'Dance under the moon!',
    topLabel: 'TOP MOONCHILDREN',
    playerLabel: 'Moonchild',
    currencyLabel: 'Moon Drops',
    powerLevelLabel: 'Lunar Power',
    achievementsLabel: 'Phases Complete',
    statCard1Label: 'Moon Drops',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'moonchildren dancing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of lunar souls!",
    rankContextText: 'Dance under the moon!',
  },
  safari: {
    title: 'SAFARI RANKINGS',
    subtitle: 'Explore the wild!',
    topLabel: 'TOP EXPLORERS',
    playerLabel: 'Explorer',
    currencyLabel: 'Safari Coins',
    powerLevelLabel: 'Animals Spotted',
    achievementsLabel: 'Safaris Complete',
    statCard1Label: 'Safari Coins',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'explorers adventuring RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of safari guides!",
    rankContextText: 'Explore the wild!',
  },
  farm: {
    title: 'FARM RANKINGS',
    subtitle: 'Grow your farm empire!',
    topLabel: 'TOP FARMERS',
    playerLabel: 'Farmer',
    currencyLabel: 'Hay Bales',
    powerLevelLabel: 'Crops Harvested',
    achievementsLabel: 'Animals Raised',
    statCard1Label: 'Hay Bales',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'farmers farming RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of farmers!",
    rankContextText: 'Grow your empire!',
  },
  candy: {
    title: 'CANDY RANKINGS',
    subtitle: 'Sweetness overload!',
    topLabel: 'TOP CANDY LOVERS',
    playerLabel: 'Candy Kid',
    currencyLabel: 'Candy Coins',
    powerLevelLabel: 'Candies Collected',
    achievementsLabel: 'Sugar Rush',
    statCard1Label: 'Candy Coins',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'candy lovers munching RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of sweet tooths!",
    rankContextText: 'Sweeten your life!',
  },
  construction: {
    title: 'CONSTRUCTION RANKINGS',
    subtitle: 'Build something amazing!',
    topLabel: 'TOP BUILDERS',
    playerLabel: 'Builder',
    currencyLabel: 'Build Bucks',
    powerLevelLabel: 'Projects Built',
    achievementsLabel: 'Tools Mastered',
    statCard1Label: 'Build Bucks',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'builders constructing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of builders!",
    rankContextText: 'Build something amazing!',
  },
  firefighter: {
    title: 'FIREFIGHTER RANKINGS',
    subtitle: 'Save the day!',
    topLabel: 'TOP FIREFIGHTERS',
    playerLabel: 'Firefighter',
    currencyLabel: 'Fire Badges',
    powerLevelLabel: 'Rescues Made',
    achievementsLabel: 'Fires Put Out',
    statCard1Label: 'Fire Badges',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'firefighters saving RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of heroes!",
    rankContextText: 'Save the day!',
  },
  ocean: {
    title: 'OCEAN RANKINGS',
    subtitle: 'Dive into adventure!',
    topLabel: 'TOP EXPLORERS',
    playerLabel: 'Explorer',
    currencyLabel: 'Sea Shells',
    powerLevelLabel: 'Depths Explored',
    achievementsLabel: 'Creatures Found',
    statCard1Label: 'Sea Shells',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'explorers diving RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of ocean explorers!",
    rankContextText: 'Dive deeper!',
  },
  jungle: {
    title: 'JUNGLE RANKINGS',
    subtitle: 'Adventure awaits!',
    topLabel: 'TOP EXPLORERS',
    playerLabel: 'Explorer',
    currencyLabel: 'Jungle Gems',
    powerLevelLabel: 'Temples Found',
    achievementsLabel: 'Animals Spotted',
    statCard1Label: 'Jungle Gems',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'explorers trekking RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of jungle explorers!",
    rankContextText: 'Conquer the jungle!',
  },
  arctic: {
    title: 'ARCTIC RANKINGS',
    subtitle: 'Brave the cold!',
    topLabel: 'TOP EXPLORERS',
    playerLabel: 'Explorer',
    currencyLabel: 'Ice Crystals',
    powerLevelLabel: 'Expeditions',
    achievementsLabel: 'Creatures Found',
    statCard1Label: 'Ice Crystals',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'explorers braving the cold RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of arctic explorers!",
    rankContextText: 'Brave the cold!',
  },
  teddy: {
    title: 'TEDDY BEAR RANKINGS',
    subtitle: 'Spread the cuddles!',
    topLabel: 'TOP TEDDIES',
    playerLabel: 'Teddy',
    currencyLabel: 'Honey Pots',
    powerLevelLabel: 'Hugs Given',
    achievementsLabel: 'Picnics Held',
    statCard1Label: 'Honey Pots',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'teddies hugging RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of cuddlers!",
    rankContextText: 'Spread the hugs!',
  },
  puppy: {
    title: 'PUPPY RANKINGS',
    subtitle: 'Good boy leaderboard!',
    topLabel: 'TOP PUPPIES',
    playerLabel: 'Puppy',
    currencyLabel: 'Puppy Treats',
    powerLevelLabel: 'Tricks Learned',
    achievementsLabel: 'Friends Made',
    statCard1Label: 'Puppy Treats',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'puppies playing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of good boys!",
    rankContextText: 'Be a good boy!',
  },
  bug: {
    title: 'BUG RANKINGS',
    subtitle: 'Explore the tiny world!',
    topLabel: 'TOP COLLECTORS',
    playerLabel: 'Collector',
    currencyLabel: 'Bug Badges',
    powerLevelLabel: 'Bugs Found',
    achievementsLabel: 'Collections',
    statCard1Label: 'Bug Badges',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'collectors collecting RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of bug hunters!",
    rankContextText: 'Catch them all!',
  },
  train: {
    title: 'TRAIN RANKINGS',
    subtitle: 'All aboard!',
    topLabel: 'TOP CONDUCTORS',
    playerLabel: 'Conductor',
    currencyLabel: 'Train Tickets',
    powerLevelLabel: 'Routes Complete',
    achievementsLabel: 'Stations Visited',
    statCard1Label: 'Train Tickets',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'conductors riding RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of conductors!",
    rankContextText: 'All aboard!',
  },
  beach: {
    title: 'BEACH RANKINGS',
    subtitle: 'Sun, sand, and success!',
    topLabel: 'TOP BEACH GOERS',
    playerLabel: 'Surfer',
    currencyLabel: 'Sand Dollars',
    powerLevelLabel: 'Waves Caught',
    achievementsLabel: 'Castles Built',
    statCard1Label: 'Sand Dollars',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'surfers catching waves RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of beach goers!",
    rankContextText: 'Catch the wave!',
  },
  camping: {
    title: 'CAMPING RANKINGS',
    subtitle: 'Pitch your tent at the top!',
    topLabel: 'TOP CAMPERS',
    playerLabel: 'Camper',
    currencyLabel: 'Campfire Logs',
    powerLevelLabel: 'Camps Made',
    achievementsLabel: 'Trails Hiked',
    statCard1Label: 'Campfire Logs',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'campers camping RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of outdoors people!",
    rankContextText: 'Pitch your tent!',
  },
  volcano: {
    title: 'VOLCANO RANKINGS',
    subtitle: 'Feel the heat!',
    topLabel: 'TOP EXPLORERS',
    playerLabel: 'Explorer',
    currencyLabel: 'Lava Rocks',
    powerLevelLabel: 'Volcanoes Climbed',
    achievementsLabel: 'Eruptions Witnessed',
    statCard1Label: 'Lava Rocks',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'explorers climbing RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of volcano explorers!",
    rankContextText: 'Feel the heat!',
  },
  planet: {
    title: 'PLANET RANKINGS',
    subtitle: 'Explore the cosmos!',
    topLabel: 'TOP EXPLORERS',
    playerLabel: 'Explorer',
    currencyLabel: 'Star Dust',
    powerLevelLabel: 'Planets Visited',
    achievementsLabel: 'Galaxies Mapped',
    statCard1Label: 'Star Dust',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'explorers traveling RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of space travelers!",
    rankContextText: 'Explore the cosmos!',
  },
  wwe: {
    title: 'CHAMPIONSHIP RANKINGS',
    subtitle: 'Battle your way to the top of the WWE Universe!',
    topLabel: 'TOP CHAMPIONS',
    playerLabel: 'Superstar',
    currencyLabel: 'Championships',
    powerLevelLabel: 'Power Level',
    achievementsLabel: 'Title Defenses',
    statCard1Label: 'Championships',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'superstars battling RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of the WWE Universe!",
    rankContextText: 'Become the champion!',
  },
  fortnite: {
    title: 'BATTLE ROYALE RANKINGS',
    subtitle: 'Drop in and claim your Victory Royale!',
    topLabel: 'TOP WARRIORS',
    playerLabel: 'Player',
    currencyLabel: 'V-Bucks',
    powerLevelLabel: 'Eliminations',
    achievementsLabel: 'Victory Royales',
    statCard1Label: 'V-Bucks',
    statCard2Label: 'Win Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'players dropping RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of warriors!",
    rankContextText: 'Get that Victory Royale!',
  },
  minecraft: {
    title: 'MASTER MINER RANKINGS',
    subtitle: 'Dig deep and craft your way to the top!',
    topLabel: 'TOP MINERS',
    playerLabel: 'Miner',
    currencyLabel: 'Diamonds',
    powerLevelLabel: 'Blocks Mined',
    achievementsLabel: 'Builds Created',
    statCard1Label: 'Diamonds',
    statCard2Label: 'Day Streak',
    statCard3Label: 'This Week',
    liveCounterText: 'miners crafting RIGHT NOW',
    topPercentText: "You're in the TOP {percent}% of miners!",
    rankContextText: 'Mine and build!',
  },
};

// Generate mock players with unified structure
export function generateMockPlayers(theme: string): LeaderboardPlayer[] {
  const baseData: Record<string, { level: number; currency: number; powerLevel: number; achievements: number }> = {
    default: { level: 95, currency: 48000, powerLevel: 12500, achievements: 245 },
    dinosaur: { level: 92, currency: 67000, powerLevel: 1580, achievements: 289 },
    battle: { level: 98, currency: 78500, powerLevel: 2450, achievements: 367 },
    builder: { level: 99, currency: 95000, powerLevel: 125000, achievements: 456 },
    unicorn: { level: 90, currency: 54000, powerLevel: 8900, achievements: 234 },
    space: { level: 96, currency: 72000, powerLevel: 45, achievements: 178 },
    robot: { level: 94, currency: 63000, powerLevel: 2890, achievements: 312 },
    pirate: { level: 92, currency: 58900, powerLevel: 324, achievements: 198 },
    monster: { level: 88, currency: 71500, powerLevel: 567, achievements: 223 },
    hero: { level: 93, currency: 66000, powerLevel: 1450, achievements: 287 },
    dreams: { level: 91, currency: 52000, powerLevel: 890, achievements: 201 },
    mermaid: { level: 89, currency: 49000, powerLevel: 2100, achievements: 195 },
    princess: { level: 90, currency: 61000, powerLevel: 345, achievements: 167 },
    rainbow: { level: 87, currency: 44000, powerLevel: 678, achievements: 189 },
    victory: { level: 100, currency: 125000, powerLevel: 8900, achievements: 534 },
    cube: { level: 99, currency: 98000, powerLevel: 450000, achievements: 892 },
    web: { level: 94, currency: 68000, powerLevel: 1230, achievements: 278 },
    creatures: { level: 97, currency: 87000, powerLevel: 456, achievements: 389 },
    glam: { level: 91, currency: 59000, powerLevel: 1120, achievements: 267 },
    fashion: { level: 92, currency: 64000, powerLevel: 890, achievements: 298 },
    ice: { level: 93, currency: 58000, powerLevel: 2340, achievements: 234 },
    pony: { level: 89, currency: 51000, powerLevel: 345, achievements: 201 },
    neon: { level: 96, currency: 82000, powerLevel: 4560, achievements: 378 },
    anime: { level: 95, currency: 52800, powerLevel: 95000, achievements: 187 },
    sneaker: { level: 90, currency: 74000, powerLevel: 567, achievements: 289 },
    esports: { level: 98, currency: 96000, powerLevel: 2340, achievements: 412 },
    aesthetic: { level: 88, currency: 47000, powerLevel: 1890, achievements: 234 },
    kpop: { level: 94, currency: 69000, powerLevel: 890, achievements: 312 },
    softgirl: { level: 86, currency: 42000, powerLevel: 1120, achievements: 178 },
    cottagecore: { level: 87, currency: 38000, powerLevel: 890, achievements: 167 },
    minimal: { level: 91, currency: 55000, powerLevel: 1450, achievements: 245 },
    cyberpunk: { level: 95, currency: 81000, powerLevel: 3450, achievements: 334 },
    coder: { level: 97, currency: 89000, powerLevel: 156000, achievements: 456 },
    streetwear: { level: 93, currency: 77000, powerLevel: 678, achievements: 301 },
    shark: { level: 90, currency: 64000, powerLevel: 2340, achievements: 267 },
    butterfly: { level: 85, currency: 36000, powerLevel: 1560, achievements: 156 },
    kitten: { level: 88, currency: 45000, powerLevel: 2340, achievements: 189 },
    fairy: { level: 89, currency: 48000, powerLevel: 1780, achievements: 201 },
    ballerina: { level: 91, currency: 56000, powerLevel: 456, achievements: 234 },
    ninja: { level: 96, currency: 73000, powerLevel: 1890, achievements: 345 },
    zombie: { level: 87, currency: 45280, powerLevel: 8847, achievements: 145 },
    racecar: { level: 94, currency: 79000, powerLevel: 678, achievements: 312 },
    mech: { level: 95, currency: 84000, powerLevel: 1560, achievements: 334 },
    popstar: { level: 92, currency: 71000, powerLevel: 890, achievements: 289 },
    cupcake: { level: 86, currency: 39000, powerLevel: 3450, achievements: 178 },
    friendship: { level: 88, currency: 46000, powerLevel: 1230, achievements: 195 },
    kawaii: { level: 89, currency: 50000, powerLevel: 1670, achievements: 212 },
    graffiti: { level: 90, currency: 62000, powerLevel: 567, achievements: 245 },
    hiphop: { level: 93, currency: 68000, powerLevel: 890, achievements: 278 },
    scifi: { level: 97, currency: 86000, powerLevel: 67, achievements: 356 },
    darkninja: { level: 94, currency: 75000, powerLevel: 2340, achievements: 312 },
    y2k: { level: 91, currency: 57000, powerLevel: 1450, achievements: 234 },
    zodiac: { level: 89, currency: 53000, powerLevel: 678, achievements: 201 },
    bookworm: { level: 92, currency: 61000, powerLevel: 1890, achievements: 267 },
    dance: { level: 90, currency: 59000, powerLevel: 567, achievements: 245 },
    lofi: { level: 88, currency: 44000, powerLevel: 1230, achievements: 189 },
    finance: { level: 96, currency: 125000, powerLevel: 4560, achievements: 389 },
    gym: { level: 94, currency: 78000, powerLevel: 8900, achievements: 334 },
    nightowl: { level: 87, currency: 46000, powerLevel: 234, achievements: 178 },
    cleangirl: { level: 89, currency: 51000, powerLevel: 890, achievements: 201 },
    sage: { level: 90, currency: 49000, powerLevel: 1120, achievements: 212 },
    coffee: { level: 91, currency: 58000, powerLevel: 2340, achievements: 245 },
    study: { level: 95, currency: 72000, powerLevel: 3450, achievements: 345 },
    parisian: { level: 92, currency: 67000, powerLevel: 678, achievements: 267 },
    wellness: { level: 88, currency: 47000, powerLevel: 1450, achievements: 195 },
    vintage: { level: 89, currency: 54000, powerLevel: 567, achievements: 212 },
    moonlight: { level: 90, currency: 56000, powerLevel: 890, achievements: 223 },
    safari: { level: 91, currency: 63000, powerLevel: 1560, achievements: 256 },
    farm: { level: 87, currency: 42000, powerLevel: 2340, achievements: 178 },
    candy: { level: 85, currency: 37000, powerLevel: 4560, achievements: 167 },
    construction: { level: 93, currency: 71000, powerLevel: 3450, achievements: 289 },
    firefighter: { level: 92, currency: 68000, powerLevel: 890, achievements: 278 },
    ocean: { level: 88, currency: 48000, powerLevel: 1890, achievements: 195 },
    jungle: { level: 90, currency: 59000, powerLevel: 567, achievements: 223 },
    arctic: { level: 89, currency: 52000, powerLevel: 234, achievements: 201 },
    teddy: { level: 84, currency: 34000, powerLevel: 2340, achievements: 156 },
    puppy: { level: 86, currency: 41000, powerLevel: 3450, achievements: 178 },
    bug: { level: 85, currency: 36000, powerLevel: 1230, achievements: 167 },
    train: { level: 88, currency: 49000, powerLevel: 678, achievements: 189 },
    beach: { level: 87, currency: 44000, powerLevel: 1560, achievements: 178 },
    camping: { level: 89, currency: 51000, powerLevel: 456, achievements: 195 },
    volcano: { level: 91, currency: 62000, powerLevel: 890, achievements: 234 },
    planet: { level: 96, currency: 78000, powerLevel: 89, achievements: 312 },
    wwe: { level: 99, currency: 85000, powerLevel: 99000, achievements: 312 },
    fortnite: { level: 100, currency: 125000, powerLevel: 8900, achievements: 534 },
    minecraft: { level: 99, currency: 98000, powerLevel: 450000, achievements: 892 },
  };

  const themeData = baseData[theme] || baseData.default;
  const avatars: Record<string, string[]> = {
    default: ['🎓', '⭐', '🏆', '💡'],
    dinosaur: ['🦖', '🦕', '🦴', '🌋'],
    battle: ['⚔️', '🛡️', '⚡', '🔥'],
    builder: ['🧱', '⛏️', '🏗️', '💎'],
    unicorn: ['🦄', '🌈', '✨', '💫'],
    space: ['🚀', '🌟', '👽', '🛸'],
    robot: ['🤖', '⚙️', '🔩', '⚡'],
    pirate: ['🏴‍☠️', '⚓', '🗺️', '💰'],
    monster: ['🚗', '🏁', '💨', '🔥'],
    hero: ['🦸', '⚡', '💥', '🛡️'],
    dreams: ['🦄', '💭', '🌈', '✨'],
    mermaid: ['🧜‍♀️', '🐚', '🌊', '💎'],
    princess: ['👑', '💎', '🏰', '✨'],
    rainbow: ['🌈', '🎨', '✨', '🌟'],
    victory: ['🏆', '⚡', '🎮', '💎'],
    cube: ['🧊', '⛏️', '💎', '🗡️'],
    web: ['🕷️', '🕸️', '💫', '⚡'],
    creatures: ['⚡', '🔥', '💧', '🌱'],
    glam: ['💅', '✨', '💄', '👗'],
    fashion: ['👗', '👠', '💃', '✨'],
    ice: ['❄️', '⛄', '💎', '🏰'],
    pony: ['🐴', '🌸', '💖', '🌈'],
    neon: ['🎮', '👾', '🕹️', '⚡'],
    anime: ['⚡', '🔥', '💨', '🌊'],
    sneaker: ['👟', '🔥', '💎', '⚡'],
    esports: ['🎮', '🏆', '⚡', '🔥'],
    aesthetic: ['✨', '🌸', '🦋', '💫'],
    kpop: ['⭐', '💜', '🎤', '✨'],
    softgirl: ['🌸', '☁️', '🦋', '✨'],
    cottagecore: ['🌿', '🍄', '🌻', '🐝'],
    minimal: ['⚪', '⚫', '🔲', '✨'],
    cyberpunk: ['🤖', '💾', '⚡', '🔮'],
    coder: ['💻', '⚡', '🔧', '🚀'],
    streetwear: ['🧥', '👟', '🔥', '💯'],
    shark: ['🦈', '🌊', '⚡', '💎'],
    butterfly: ['🦋', '🌸', '🌺', '✨'],
    kitten: ['🐱', '🎀', '💖', '✨'],
    fairy: ['🧚', '✨', '🌸', '💫'],
    ballerina: ['🩰', '👑', '✨', '🌸'],
    ninja: ['🥷', '⚔️', '💨', '⚡'],
    zombie: ['🧟', '💣', '🔪', '🪓'],
    racecar: ['🏎️', '🏁', '⚡', '🔥'],
    mech: ['🤖', '⚙️', '⚡', '🛡️'],
    popstar: ['⭐', '🎤', '💿', '✨'],
    cupcake: ['🧁', '🎂', '🍰', '✨'],
    friendship: ['💖', '🌈', '✨', '🦄'],
    kawaii: ['🌸', '🎀', '💕', '✨'],
    graffiti: ['🎨', '💥', '🔥', '⚡'],
    hiphop: ['🎤', '🎵', '🔥', '👑'],
    scifi: ['🛸', '⚡', '🔮', '🌌'],
    darkninja: ['🥷', '⚫', '⚔️', '💀'],
    y2k: ['💿', '📱', '✨', '🦋'],
    zodiac: ['⭐', '🌙', '✨', '🔮'],
    bookworm: ['📚', '📖', '✨', '🎓'],
    dance: ['💃', '🕺', '✨', '🎵'],
    lofi: ['🎧', '🎵', '☕', '✨'],
    finance: ['💰', '📈', '💎', '🏆'],
    gym: ['💪', '🏋️', '🔥', '⚡'],
    nightowl: ['🦉', '🌙', '⭐', '✨'],
    cleangirl: ['🤍', '✨', '🌸', '💫'],
    sage: ['🌿', '🍃', '✨', '🧘'],
    coffee: ['☕', '🤎', '✨', '🌟'],
    study: ['✏️', '📚', '🎓', '⭐'],
    parisian: ['🗼', '🥐', '👗', '✨'],
    wellness: ['🧘', '🌿', '✨', '💆'],
    vintage: ['📻', '🎙️', '✨', '🎶'],
    moonlight: ['🌙', '✨', '💫', '🌟'],
    safari: ['🦁', '🐘', '🦒', '🌍'],
    farm: ['🐮', '🌾', '🚜', '🌻'],
    candy: ['🍭', '🍬', '🍫', '✨'],
    construction: ['🚜', '🏗️', '⚡', '🔨'],
    firefighter: ['🚒', '🔥', '💪', '🏅'],
    ocean: ['🐠', '🐙', '🐚', '🌊'],
    jungle: ['🐒', '🦍', '🌴', '🌺'],
    arctic: ['🐧', '❄️', '🐻‍❄️', '⛄'],
    teddy: ['🧸', '🍯', '🌸', '✨'],
    puppy: ['🐶', '🦴', '💖', '⚡'],
    bug: ['🐛', '🐝', '🦋', '🌸'],
    train: ['🚂', '🚃', '🛤️', '⚡'],
    beach: ['🏖️', '🌊', '🐚', '🏄'],
    camping: ['⛺', '🔥', '🌲', '🌙'],
    volcano: ['🌋', '🔥', '💎', '⚡'],
    planet: ['🪐', '⭐', '🌌', '🚀'],
    wwe: ['🏆', '💪', '👑', '⚡'],
    fortnite: ['🎮', '⚡', '🔥', '💎'],
    minecraft: ['💎', '⛏️', '🔥', '⚒️'],
  };

  const topNames: Record<string, string[]> = {
    default: ['StudyMaster', 'BrainPower', 'TopLearner'],
    dinosaur: ['RexKing', 'VelocityHunter', 'FossilFinder'],
    battle: ['WarriorPro', 'BattleLegend', 'FightMaster'],
    builder: ['BlockMaster', 'CraftKing', 'BuildLegend'],
    unicorn: ['MagicHorn', 'RainbowDream', 'SparkleQueen'],
    space: ['StarExplorer', 'GalaxyRider', 'CosmicHero'],
    robot: ['CyberBot9000', 'MechMaster', 'CircuitKing'],
    pirate: ['CaptainBlackbeard', 'SeaDragon', 'TreasureHunter'],
    monster: ['TurboKing', 'CrusherMax', 'JumpMaster'],
    hero: ['SuperSaver', 'MightyHero', 'PowerChamp'],
    dreams: ['DreamWeaver', 'RainbowRider', 'MagicDreamer'],
    mermaid: ['CoralQueen', 'TidePrincess', 'WaveMaster'],
    princess: ['RoyalGrace', 'CastleQueen', 'DiamondPrincess'],
    rainbow: ['ColorMaster', 'PrismPainter', 'RainbowArtist'],
    victory: ['VictoryKing', 'RoyaleChamp', 'LootMaster'],
    cube: ['CraftPro', 'DiamondMiner', 'BuildKing'],
    web: ['WebSlinger', 'WallCrawler', 'HeroSwing'],
    creatures: ['PokeMaster', 'TrainerPro', 'CatchKing'],
    glam: ['GlamQueen', 'SparkleGirl', 'StyleIcon'],
    fashion: ['RunwayQueen', 'DesignStar', 'FashionIcon'],
    ice: ['FrostQueen', 'IcePrincess', 'SnowMaster'],
    pony: ['HorseWhisperer', 'GallopStar', 'PonyPro'],
    neon: ['PixelKing', 'GamerPro', 'LevelMax'],
    anime: ['ShadowHokage', 'DragonFist', 'PhoenixRising'],
    sneaker: ['SneakerKing', 'HypeBeast', 'KickCollector'],
    esports: ['ProGamer99', 'TourneyKing', 'MVPLegend'],
    aesthetic: ['VibeQueen', 'AestheticStar', 'CloudDreamer'],
    kpop: ['IdolStar', 'PopQueen', 'StageKing'],
    softgirl: ['CloudGirl', 'SoftVibes', 'DreamyQueen'],
    cottagecore: ['GardenGirl', 'CottageSoul', 'NatureLover'],
    minimal: ['MinimalKing', 'CleanVibes', 'SimpleLife'],
    cyberpunk: ['NetRunner', 'CyberHawk', 'GridMaster'],
    coder: ['CodeNinja', 'DevMaster', 'BugDestroyer'],
    streetwear: ['HypeBeast', 'DrippyKing', 'StreetLegend'],
    shark: ['OceanPredator', 'SharkKing', 'DeepHunter'],
    butterfly: ['FlutterQueen', 'WingBeauty', 'GardenAngel'],
    kitten: ['WhiskerQueen', 'PurrMaster', 'CuddleKing'],
    fairy: ['PixieDust', 'MagicWings', 'FairyQueen'],
    ballerina: ['SwanQueen', 'GraceDancer', 'BalletStar'],
    ninja: ['ShadowBlade', 'SilentStrike', 'NinjaMaster'],
    zombie: ['ZombieSlayer99', 'ApocalypsePro', 'LastStanding'],
    racecar: ['SpeedDemon', 'RaceKing', 'TurboMaster'],
    mech: ['MechPilot', 'RobotCommander', 'GearMaster'],
    popstar: ['StageStar', 'PopIcon', 'MusicLegend'],
    cupcake: ['BakeryQueen', 'SweetMaster', 'FrostingKing'],
    friendship: ['BFFForever', 'SquadLeader', 'FriendlyHeart'],
    kawaii: ['KawaiiQueen', 'CuteKing', 'SugarStar'],
    graffiti: ['SprayMaster', 'UrbanArtist', 'WallKing'],
    hiphop: ['MCMaster', 'BeatDrop', 'RapKing'],
    scifi: ['QuantumRider', 'FutureMaster', 'TechHero'],
    darkninja: ['DarkBlade', 'ShadowAssassin', 'NightStriker'],
    y2k: ['RetroKing', 'Y2KQueen', 'GlitterStar'],
    zodiac: ['StarReader', 'CosmicSage', 'ZodiacMaster'],
    bookworm: ['PageTurner', 'BookMaster', 'ReadingPro'],
    dance: ['DanceKing', 'MoveQueen', 'RhythmMaster'],
    lofi: ['ChillVibes', 'LofiKing', 'CalmBeats'],
    finance: ['CryptoKing', 'TraderPro', 'MoneyMaster'],
    gym: ['GainsMaster', 'LiftKing', 'MuscleChamp'],
    nightowl: ['MidnightHawk', 'NightMaster', 'MoonOwl'],
    cleangirl: ['GlowQueen', 'CleanVibes', 'PureBeauty'],
    sage: ['ZenMaster', 'CalmSoul', 'WiseSage'],
    coffee: ['BaristaKing', 'BrewMaster', 'CaffeinePro'],
    study: ['StudyKing', 'AceScholar', 'TopStudent'],
    parisian: ['ChicQueen', 'ParisStyle', 'ElegantSoul'],
    wellness: ['ZenGuru', 'BalanceMaster', 'WellnessKing'],
    vintage: ['RetroSoul', 'VintageQueen', 'ClassicKing'],
    moonlight: ['LunarQueen', 'MoonChild', 'NightStar'],
    safari: ['SafariKing', 'WildExplorer', 'JungleScout'],
    farm: ['FarmerPro', 'HarvestKing', 'BarnMaster'],
    candy: ['SugarKing', 'CandyQueen', 'SweetTooth'],
    construction: ['BuilderPro', 'ConstructKing', 'ToolMaster'],
    firefighter: ['BraveHero', 'FireChief', 'RescuePro'],
    ocean: ['SeaExplorer', 'CoralKing', 'OceanPro'],
    jungle: ['JungleKing', 'WildExplorer', 'TreeMaster'],
    arctic: ['IceExplorer', 'PolarKing', 'FrostMaster'],
    teddy: ['HugMaster', 'TeddyKing', 'CuddleBear'],
    puppy: ['GoodBoy', 'PuppyPro', 'TailWagger'],
    bug: ['BugMaster', 'InsectKing', 'CritterPro'],
    train: ['ConductorPro', 'TrainMaster', 'RailKing'],
    beach: ['SurfKing', 'BeachPro', 'WaveRider'],
    camping: ['CampMaster', 'OutdoorPro', 'TrailKing'],
    volcano: ['LavaKing', 'VolcanoPro', 'FireMaster'],
    planet: ['SpaceExplorer', 'PlanetHopper', 'CosmicTraveler'],
    wwe: ['The Rock Jr', 'Stone Cold Sam', 'Triple H Kid'],
    fortnite: ['TTV_BushrookKid', 'NinjaPro2024', 'StormKing'],
    minecraft: ['DiamondSteve', 'EnderDragonKiller', 'RedstoneMaster'],
  };

  const themeAvatars = avatars[theme] || avatars.default;
  const themeNames = topNames[theme] || topNames.default;

  return [
    { rank: 1, name: themeNames[0], level: themeData.level, currency: themeData.currency, powerLevel: themeData.powerLevel, achievements: themeData.achievements, change: 0, avatar: themeAvatars[0] },
    { rank: 2, name: themeNames[1], level: themeData.level - 3, currency: Math.floor(themeData.currency * 0.92), powerLevel: Math.floor(themeData.powerLevel * 0.93), achievements: Math.floor(themeData.achievements * 0.93), change: 1, avatar: themeAvatars[1] },
    { rank: 3, name: themeNames[2], level: themeData.level - 6, currency: Math.floor(themeData.currency * 0.85), powerLevel: Math.floor(themeData.powerLevel * 0.88), achievements: Math.floor(themeData.achievements * 0.86), change: -1, avatar: themeAvatars[2] },
    ...Array.from({ length: 97 }, (_, i) => ({
      rank: i + 4,
      name: `${themeLeaderboardConfig[theme].playerLabel}${i + 4}`,
      level: themeData.level - 7 - i,
      currency: Math.floor(themeData.currency * 0.82 - (i * (themeData.currency * 0.008))),
      powerLevel: Math.floor(themeData.powerLevel * 0.86 - (i * (themeData.powerLevel * 0.008))),
      achievements: Math.floor(themeData.achievements * 0.80 - (i * (themeData.achievements * 0.008))),
      change: Math.floor(Math.random() * 11) - 5,
      avatar: themeAvatars[i % themeAvatars.length],
    })),
  ];
}
