/*
  # Fix Curriculum Skills Data and Schema

  ## Changes Made
  
  1. Schema Updates
     - Add `skill_code` column (TEXT, UNIQUE) - unique identifier for each skill
     - Add `description` column (TEXT) - detailed explanation of the skill
     - Add `display_order` column (INTEGER) - controls UI sequence
     - Add `is_active` column (BOOLEAN) - enable/disable skills
  
  2. Data Reset
     - Delete all existing curriculum_skills rows (wrong skills from old schema)
     - Insert foundational skills for all 6 subjects
  
  3. New Skills Added
     - MATH: 10 skills (counting, addition, subtraction, multiplication, division, fractions)
     - READ: 5 skills (phonics, sight words, comprehension K-2)
     - SPELL: 5 skills (CVC, blends, digraphs, silent E, vowel teams)
     - TYPE: 5 skills (home row, top row, bottom row, numbers, speed building)
     - CODE: 5 skills (sequences, events, loops, conditionals, variables)
     - LANG: 6 skills (sentences, nouns, verbs, adjectives, punctuation, paragraphs)
  
  ## Important Notes
  - This is a STARTER set of foundational skills
  - Full K-12 curriculum will be generated by Grok later
  - Grade levels range from 0 (Kindergarten) to 12 (12th grade)
  - Difficulty levels: 1=easy, 2=medium, 3=hard
  - Each skill has subject_code, skill_code, name, description, grade, difficulty, and display order
*/

-- Add new columns to curriculum_skills
DO $$
BEGIN
  -- Add skill_code column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'curriculum_skills' AND column_name = 'skill_code'
  ) THEN
    ALTER TABLE curriculum_skills 
    ADD COLUMN skill_code text;
  END IF;

  -- Add description column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'curriculum_skills' AND column_name = 'description'
  ) THEN
    ALTER TABLE curriculum_skills 
    ADD COLUMN description text;
  END IF;

  -- Add display_order column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'curriculum_skills' AND column_name = 'display_order'
  ) THEN
    ALTER TABLE curriculum_skills 
    ADD COLUMN display_order integer DEFAULT 0;
  END IF;

  -- Add is_active column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'curriculum_skills' AND column_name = 'is_active'
  ) THEN
    ALTER TABLE curriculum_skills 
    ADD COLUMN is_active boolean DEFAULT true;
  END IF;
END $$;

-- Delete all existing skills (wrong data from old schema)
DELETE FROM curriculum_skills;

-- Add UNIQUE constraint to skill_code if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'curriculum_skills_skill_code_key'
  ) THEN
    ALTER TABLE curriculum_skills 
    ADD CONSTRAINT curriculum_skills_skill_code_key UNIQUE (skill_code);
  END IF;
END $$;

-- Insert foundational skills for all 6 subjects

-- MATH SKILLS (10 foundational skills)
INSERT INTO curriculum_skills (subject_code, skill_code, skill_name, description, grade_level, difficulty_level, display_order, is_active) VALUES
('MATH', 'math_counting', 'Counting', 'Count objects and numbers 1-100', 0, 1, 1, true),
('MATH', 'math_addition_basic', 'Addition Basics', 'Add numbers within 10', 0, 1, 2, true),
('MATH', 'math_subtraction_basic', 'Subtraction Basics', 'Subtract numbers within 10', 0, 1, 3, true),
('MATH', 'math_addition_20', 'Addition to 20', 'Add numbers within 20', 1, 1, 4, true),
('MATH', 'math_subtraction_20', 'Subtraction to 20', 'Subtract numbers within 20', 1, 1, 5, true),
('MATH', 'math_place_value', 'Place Value', 'Understand tens and ones', 1, 2, 6, true),
('MATH', 'math_multiplication_intro', 'Multiplication Introduction', 'Understand multiplication as repeated addition', 2, 2, 7, true),
('MATH', 'math_multiplication_facts', 'Multiplication Facts', 'Memorize times tables 1-10', 3, 2, 8, true),
('MATH', 'math_division_intro', 'Division Introduction', 'Understand division as splitting into groups', 3, 2, 9, true),
('MATH', 'math_fractions_intro', 'Fractions Introduction', 'Understand parts of a whole', 3, 2, 10, true);

-- READ SKILLS (5 foundational skills)
INSERT INTO curriculum_skills (subject_code, skill_code, skill_name, description, grade_level, difficulty_level, display_order, is_active) VALUES
('READ', 'read_phonics_basic', 'Basic Phonics', 'Letter sounds and CVC words', 0, 1, 1, true),
('READ', 'read_sight_words', 'Sight Words', 'Common words that must be memorized', 0, 1, 2, true),
('READ', 'read_comprehension_k', 'Reading Comprehension K', 'Understand simple stories', 0, 1, 3, true),
('READ', 'read_comprehension_1', 'Reading Comprehension 1st', 'Answer questions about stories', 1, 1, 4, true),
('READ', 'read_comprehension_2', 'Reading Comprehension 2nd', 'Identify main idea and details', 2, 2, 5, true);

-- SPELL SKILLS (5 foundational skills)
INSERT INTO curriculum_skills (subject_code, skill_code, skill_name, description, grade_level, difficulty_level, display_order, is_active) VALUES
('SPELL', 'spell_cvc', 'CVC Words', 'Consonant-vowel-consonant words', 0, 1, 1, true),
('SPELL', 'spell_blends', 'Blends', 'Two consonants together (bl, st, tr)', 1, 1, 2, true),
('SPELL', 'spell_digraphs', 'Digraphs', 'Two letters one sound (sh, ch, th)', 1, 1, 3, true),
('SPELL', 'spell_silent_e', 'Silent E Rule', 'Magic E makes vowel say its name', 1, 2, 4, true),
('SPELL', 'spell_vowel_teams', 'Vowel Teams', 'Two vowels together (ai, ay, ee, oa)', 2, 2, 5, true);

-- TYPE SKILLS (5 foundational skills)
INSERT INTO curriculum_skills (subject_code, skill_code, skill_name, description, grade_level, difficulty_level, display_order, is_active) VALUES
('TYPE', 'type_home_row', 'Home Row Keys', 'Learn a,s,d,f,j,k,l,;', 1, 1, 1, true),
('TYPE', 'type_top_row', 'Top Row Keys', 'Learn q,w,e,r,t,y,u,i,o,p', 1, 2, 2, true),
('TYPE', 'type_bottom_row', 'Bottom Row Keys', 'Learn z,x,c,v,b,n,m', 1, 2, 3, true),
('TYPE', 'type_numbers', 'Number Keys', 'Learn 1-0 on top row', 2, 2, 4, true),
('TYPE', 'type_speed_20', 'Speed Building 20 WPM', 'Build speed to 20 words per minute', 3, 2, 5, true);

-- CODE SKILLS (5 foundational skills)
INSERT INTO curriculum_skills (subject_code, skill_code, skill_name, description, grade_level, difficulty_level, display_order, is_active) VALUES
('CODE', 'code_sequences', 'Sequences', 'Step-by-step instructions in order', 0, 1, 1, true),
('CODE', 'code_events', 'Events', 'When something happens, do something', 0, 1, 2, true),
('CODE', 'code_loops', 'Loops', 'Repeat actions multiple times', 1, 2, 3, true),
('CODE', 'code_conditionals', 'Conditionals', 'If-then decisions', 2, 2, 4, true),
('CODE', 'code_variables', 'Variables', 'Store and use information', 3, 3, 5, true);

-- LANG SKILLS (6 foundational skills - Language Arts / Grammar)
INSERT INTO curriculum_skills (subject_code, skill_code, skill_name, description, grade_level, difficulty_level, display_order, is_active) VALUES
('LANG', 'lang_sentences', 'Complete Sentences', 'Subject + verb + complete thought', 1, 1, 1, true),
('LANG', 'lang_nouns', 'Nouns', 'Person, place, thing, or idea', 1, 1, 2, true),
('LANG', 'lang_verbs', 'Verbs', 'Action words and being words', 1, 1, 3, true),
('LANG', 'lang_adjectives', 'Adjectives', 'Words that describe nouns', 2, 1, 4, true),
('LANG', 'lang_punctuation', 'Punctuation', 'Periods, question marks, exclamation points', 2, 1, 5, true),
('LANG', 'lang_paragraphs', 'Paragraphs', 'Topic sentence, supporting sentences, closing', 3, 2, 6, true);