/*
  # Self-Monitoring AI System

  ## Overview
  Enables automatic detection of student struggles, system issues, and learning patterns.
  Generates alerts for parents and provides insights for the AI tutor.

  ## Tables

  ### `monitoring_alerts`
  Stores alerts generated by the monitoring system

  ### `monitoring_insights`
  Stores AI-generated insights about student learning

  ### `daily_summaries`
  Stores daily summaries of student activity
*/

-- Monitoring Alerts Table
CREATE TABLE IF NOT EXISTS monitoring_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id uuid NOT NULL REFERENCES children(id) ON DELETE CASCADE,
  family_id uuid REFERENCES families(id) ON DELETE CASCADE,

  -- Alert classification
  alert_type text NOT NULL CHECK (alert_type IN (
    'struggling', 'inactive', 'streak_broken', 'low_accuracy',
    'frustration_detected', 'milestone_achieved', 'improvement',
    'subject_weakness', 'test_reminder', 'celebration'
  )),
  severity text NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'urgent')),

  -- Alert content
  title text NOT NULL,
  message text NOT NULL,
  subject_code text,

  -- Context data
  data jsonb DEFAULT '{}',

  -- Status tracking
  is_read boolean DEFAULT false,
  is_dismissed boolean DEFAULT false,
  action_taken text,

  -- Timestamps
  created_at timestamptz DEFAULT now(),
  read_at timestamptz,
  dismissed_at timestamptz
);

-- Monitoring Insights Table (AI-generated observations)
CREATE TABLE IF NOT EXISTS monitoring_insights (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id uuid NOT NULL REFERENCES children(id) ON DELETE CASCADE,

  -- Insight classification
  insight_type text NOT NULL CHECK (insight_type IN (
    'learning_pattern', 'best_time', 'subject_strength', 'subject_weakness',
    'pace_recommendation', 'encouragement_style', 'break_pattern', 'focus_time'
  )),

  -- Insight content
  title text NOT NULL,
  description text NOT NULL,
  recommendation text,
  confidence float DEFAULT 0.5 CHECK (confidence >= 0 AND confidence <= 1),

  -- Source data
  based_on_questions integer DEFAULT 0,
  based_on_sessions integer DEFAULT 0,
  data jsonb DEFAULT '{}',

  -- Validity
  valid_until timestamptz DEFAULT (now() + interval '30 days'),
  is_active boolean DEFAULT true,

  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Daily Activity Summaries
CREATE TABLE IF NOT EXISTS daily_summaries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id uuid NOT NULL REFERENCES children(id) ON DELETE CASCADE,
  summary_date date NOT NULL DEFAULT CURRENT_DATE,

  -- Activity metrics
  questions_answered integer DEFAULT 0,
  questions_correct integer DEFAULT 0,
  accuracy float DEFAULT 0,

  lessons_completed integer DEFAULT 0,
  time_spent_minutes integer DEFAULT 0,
  coins_earned integer DEFAULT 0,

  -- Subject breakdown
  subject_breakdown jsonb DEFAULT '{}',

  -- Streaks and milestones
  streak_maintained boolean DEFAULT false,
  milestones_achieved text[] DEFAULT ARRAY[]::text[],

  -- AI observations
  ai_notes text,
  mood_detected text CHECK (mood_detected IN ('frustrated', 'neutral', 'engaged', 'excited')),

  created_at timestamptz DEFAULT now(),

  -- One summary per child per day
  UNIQUE(child_id, summary_date)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_monitoring_alerts_child_id ON monitoring_alerts(child_id);
CREATE INDEX IF NOT EXISTS idx_monitoring_alerts_family_id ON monitoring_alerts(family_id);
CREATE INDEX IF NOT EXISTS idx_monitoring_alerts_unread ON monitoring_alerts(child_id, is_read) WHERE NOT is_read;
CREATE INDEX IF NOT EXISTS idx_monitoring_insights_child_id ON monitoring_insights(child_id);
CREATE INDEX IF NOT EXISTS idx_daily_summaries_child_date ON daily_summaries(child_id, summary_date DESC);

-- RLS Policies
ALTER TABLE monitoring_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE monitoring_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_summaries ENABLE ROW LEVEL SECURITY;

-- Alerts policies
CREATE POLICY "Users can view alerts for their family"
  ON monitoring_alerts FOR SELECT
  USING (
    family_id IN (SELECT id FROM families WHERE user_id = auth.uid())
    OR
    child_id IN (SELECT id FROM children WHERE family_id IN (SELECT id FROM families WHERE user_id = auth.uid()))
  );

CREATE POLICY "Users can update their family alerts"
  ON monitoring_alerts FOR UPDATE
  USING (
    family_id IN (SELECT id FROM families WHERE user_id = auth.uid())
    OR
    child_id IN (SELECT id FROM children WHERE family_id IN (SELECT id FROM families WHERE user_id = auth.uid()))
  );

CREATE POLICY "Service role has full access to alerts"
  ON monitoring_alerts FOR ALL
  USING (auth.role() = 'service_role');

-- Insights policies
CREATE POLICY "Users can view insights for their children"
  ON monitoring_insights FOR SELECT
  USING (
    child_id IN (SELECT id FROM children WHERE family_id IN (SELECT id FROM families WHERE user_id = auth.uid()))
  );

CREATE POLICY "Service role has full access to insights"
  ON monitoring_insights FOR ALL
  USING (auth.role() = 'service_role');

-- Daily summaries policies
CREATE POLICY "Users can view summaries for their children"
  ON daily_summaries FOR SELECT
  USING (
    child_id IN (SELECT id FROM children WHERE family_id IN (SELECT id FROM families WHERE user_id = auth.uid()))
  );

CREATE POLICY "Service role has full access to daily summaries"
  ON daily_summaries FOR ALL
  USING (auth.role() = 'service_role');

-- Add monitoring-related columns to children if not exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'children' AND column_name = 'last_activity_at'
  ) THEN
    ALTER TABLE children ADD COLUMN last_activity_at timestamptz DEFAULT now();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'children' AND column_name = 'consecutive_wrong_answers'
  ) THEN
    ALTER TABLE children ADD COLUMN consecutive_wrong_answers integer DEFAULT 0;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'children' AND column_name = 'total_sessions'
  ) THEN
    ALTER TABLE children ADD COLUMN total_sessions integer DEFAULT 0;
  END IF;
END $$;

-- Comments
COMMENT ON TABLE monitoring_alerts IS 'AI-generated alerts about student progress, struggles, and achievements';
COMMENT ON TABLE monitoring_insights IS 'Long-term AI insights about learning patterns and recommendations';
COMMENT ON TABLE daily_summaries IS 'Daily activity summaries for each student';
